---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages (Debian/Ubuntu)
  apt:
    name:
      - unzip
      - python3-apt
    state: present
