---
- name: Check if agent directory exists
  ansible.builtin.stat:
    path: "{{ dc_agent_install_dir }}/dcagent"
  register: dcagent_dir

- name: Create agent directory
  ansible.builtin.file:
    path: "{{ dc_agent_install_dir }}/dcagent"
    state: directory
    owner: "{{ dc_agent_username }}"
    group: "{{ dc_agent_username }}"
    mode: '0755'
  when: not dcagent_dir.stat.exists

- name: Download Desktop Central Agent
  ansible.builtin.get_url:
    url: "{{ dc_agent_url }}"
    dest: "{{ dc_agent_install_dir }}/dcagent/UEMS_LinuxAgent.bin"
    mode: '0755'
    validate_certs: false
  register: download_result

- name: Check if installation directory exists
  ansible.builtin.stat:
    path: "{{ dc_directory }}"
  register: install_dir

- name: Install Desktop Central Agent
  ansible.builtin.command:
    cmd: "./UEMS_LinuxAgent.bin {% if dc_force_install %}-f{% endif %}"
    chdir: "{{ dc_agent_install_dir }}/dcagent"
  become: true
  when: not install_dir.stat.exists or dc_force_install
