---
- name: Check if agent directory exists
  ansible.builtin.stat:
    path: "{{ dc_agent_install_dir }}/dcagent"
  register: dcagent_dir

- name: Create agent directory
  ansible.builtin.file:
    path: "{{ dc_agent_install_dir }}/dcagent"
    state: directory
    owner: "{{ dc_agent_username }}"
    group: "{{ dc_agent_username }}"
    mode: '0755'
  when: not dcagent_dir.stat.exists

- name: Download Desktop Central Agent
  ansible.builtin.get_url:
    url: "{{ dc_agent_url }}"
    dest: "{{ dc_agent_install_dir }}/dcagent/dcagent.zip"
    mode: '0755'
    validate_certs: false
  register: download_result

- name: Extract Desktop Central Agent
  ansible.builtin.unarchive:
    src: "{{ dc_agent_install_dir }}/dcagent/dcagent.zip"
    dest: "{{ dc_agent_install_dir }}/dcagent"
  when: download_result is changed

- name: Check if Desktop Central Agent is already installed
  ansible.builtin.stat:
    path: "{{ dc_agent_install_dir }}/dcagent/UEMS_LinuxAgent.bin"
  register: dcagent_installed

- name: Install Desktop Central Agent
  ansible.builtin.command:
    cmd: "./UEMS_LinuxAgent.bin {% if dc_force_install %}-f{% endif %}"
    chdir: "{{ dc_agent_install_dir }}/dcagent"
  become: true
  when: not dcagent_installed.stat.exists or dc_force_install
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and not dc_force_install
