---
- name: Verify required variables
  assert:
    that:
      - dc_agent_url != ""
    fail_msg: "Required variable dc_agent_url is not set"

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Include installation tasks
  include_tasks: install.yml