---
- name: Check if installation directory exists
  ansible.builtin.stat:
    path: "{{ manageengine_agent_install_dir }}"
  register: install_dir_status

- name: Validate ManageEngine agent installation
  ansible.builtin.command: "{{ manageengine_agent_executable }} --version"
  when: install_dir_status.stat.exists
  register: agent_version_check
  failed_when: "'version' not in agent_version_check.stdout"
  tags: manageengine_agent_validate
